#!/bin/bash
#SBATCH --job-name=foldseek
#SBATCH --auks=yes                                      # use Kerberos
#SBATCH --partition=cpu                                 # possible values: cpu, gpu
#SBATCH --ntasks=1                                      # Number of tasks (default=1)
#SBATCH --cpus-per-task=16                               # number of cpus for this task (default=1)
#SBATCH --mem=32G                                       # size of memory (default 10G in cpu and gpu)
#SBATCH --nodes=1                                       # Ensure that all cores are on one machine
#SBATCH --output=job_%j.out                             # File to which standard out will be written
#SBATCH --error=job_%j.err                              # File to which standard err will be written
#SBATCH --mail-type=END                                 # Type of email notification- BEGIN,END,FAIL,ALL
#SBATCH --mail-user=tan@ipk-gatersleben.de  # Email to which notifications will be sent

# === Configuration ===
BASE_DIR="${BASE_DIR:-/filer-5/agruppen/PBP/tan}"

module load foldseek

# Path
cd /filer-5/user/tan/evolution/crp/new/alphafold_barley/Poaceae_esmfold_res

# Create db
foldseek createdb . ../crp_db

# Running
# --alignment-type 1:  3Di+AA 
foldseek search ../crp_db ../crp_db ../all_vs_all_res ../tmp \
    --alignment-type 1 \
    -a 1 \
    --threads 16 \
    --tmscore-threshold 0.3

# output as readable format
# query, target, alntmscore (TM-score)
foldseek convertalis ../crp_db ../crp_db ../all_vs_all_res ../all_vs_all.tab \
    --format-output "query,target,alntmscore,rmsd,lddt,fident,alnlen,evalue"

